Harmony Standards proposal
mobilejazz/harmony-reference pull request #96
Opened 2021-10-22 10:44 UTC by doup

Hi! Following the [Asana task](https://app.asana.com/0/1200574432121296/1201083980462269/f) where I suggested the usage of the reference as a standards repository, here is a proof of concept and the first meta-standard proposal.

This is how it would look in the Harmony Reference:

![image](https://user-images.githubusercontent.com/188612/138441022-d0846c8b-cb86-423b-ae27-5958e40ca53f.png)

2021-11-26 07:40 UTC, vilanovi commented
It's a simple way to organize little pieces of information. My question is do we have enough standards to build a meaningful enough repository of standards? do we feel we will actually use it beyond the regular harmony documentation?

I'm asking as we already are struggling to document the regular site of harmony, and this adds a new dimension and it will rerquire work.

Your thoughts @Alex-DA @franmontiel?

2021-11-26 14:13 UTC, franmontiel commented
I like the approach of separating the "standards" into his own tab.

Here are some doubts and comments about it:

- Standards will be used for workflows as QA, PRs, Git flow usage, etc? Or they will also include standards related to coding?
  - In my opinion, those two concepts must be separated to have a better organization. We can keep code-related standards on Reference or create his own tab (keeping them on the reference for the moment has no extra work and we can decide about it later)

- The naming of the standard does provide any advantage over having a more human-readable organization?:   
  - e.g: 001-pull-request vs Pull requests 
  - If it grows or there are some specific workflows for backend/frontend/mobile we can always use sections to organize them

2021-11-29 08:03 UTC, doup commented
How I see it:

- I don't think it's a matter of how much standards we have[0]. Standards are their own entity: things that must be complied with, this would be the place for all that.
- So if it must be complied with, then it's a standard: be it code related or workflow related.
- I think this is a completely separate thing from the reference (although we could skip the new tab and put it on the sidebar)
- I agree Monti, probably is better to structure this in a more human readable fashion.
    - For me it's OK if we skip the XXX naming and maybe also the RFC keywords (or we could use something simplified, maybe just: required & recommended)

@vilanovi regarding efforts, totally true, it'll require work, but on the other side I see that we've decided upon things that afterwards are forgotten or new team members are not aware of because these agreements had poor discoverability. This would solve this and other problems.

Related to documentation state, I think we should be moving to the "documentation standard", and clarify the types of docs we want to have… but that's another thing that takes time and only pays on the long run. 😭 

0: In web we know we've at least 5~ things we want to standardise

2021-12-03 15:35 UTC, franmontiel requested changes
Regarding our comments, seems we agree on removing numbering & organizing it in a more human-readable way.

If we can change the meta-standard to not mention the numbering and to change the way of naming we can merge and start adding content.

2021-12-10 09:03 UTC, Alex-DA commented
Continue on https://app.asana.com/0/1200574432121296/1201083980462269

2021-12-24 16:00 UTC, doup commented
I've updated this after a discussion on the Frontend Tech Monthly meeting. For me it's clear we need this to improve our processes.

**Updated:**
![image](https://user-images.githubusercontent.com/188612/147363374-bc68d188-a6f1-4fa0-af99-26c1448344c8.png)

2022-05-19 11:59 UTC, doup commented
Closing this since there is no interest.

2022-05-19 11:59 UTC, closed without merging